import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '../components/navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />

        <main
          className="
            mt-16
            p-8
            min-h-screen
            flex flex-col
            gap-6
            bg-[radial-gradient(circle_at_top_left,rgba(56,189,248,0.04),transparent),radial-gradient(circle_at_bottom_right,rgba(79,70,229,0.06),transparent),#020817]
          "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
