// src/app/weather/components/weather-cards-loader.jsx
'use client';

import { useEffect, useState } from 'react';
import { hydrateStoreFromSupabase } from '@/app/lib/weather/sync';
import WeatherCardsSkeletonList from './weather-cards-skeleton-list';

/**
 * The following component was generated by Cursor
 */

// Module-level cache to prevent multiple hydrations
let hydrationPromise = null;
let isHydrated = false;

export default function WeatherCardsLoader({ children }) {
  // Start with false, but only show skeleton after mount (client-side)
  const [isReady, setIsReady] = useState(false);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    // Mark as mounted (client-side only)
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsMounted(true);

    // Only run in browser
    if (typeof window === 'undefined') {
      return;
    }

    // If already hydrated, we're done
    if (isHydrated) {
      setIsReady(true);
      return;
    }

    // If promise already exists, wait for it
    if (hydrationPromise) {
      hydrationPromise
        .then(() => {
          setIsReady(true);
        })
        .catch(() => {
          // On error, allow retry
          hydrationPromise = null;
          isHydrated = false;
        });
      return;
    }

    // Create new hydration promise
    hydrationPromise = hydrateStoreFromSupabase()
      .then((result) => {
        isHydrated = true;
        hydrationPromise = null;
        setIsReady(true);
        return result;
      })
      .catch((error) => {
        hydrationPromise = null;
        isHydrated = false;
        console.error('Hydration failed:', error);
        // Don't set isReady on error - component will show error state
      });
  }, []);

  // Don't render anything until mounted (prevents hydration mismatch)
  if (!isMounted) {
    return null;
  }

  // Show skeleton while not ready
  if (!isReady) {
    return <WeatherCardsSkeletonList count={3} />;
  }

  return children;
}
