// src/app/weather/components/weather-cards-skeleton-list.jsx
'use client';

import React from 'react';
import WeatherCardSkeleton from './weather-card-skeleton';

/**
 * The following component was generated by Cursor
 */
export default function WeatherCardsSkeletonList({ count = 3 }) {
  return (
    <div
      className="
        grid
        [grid-template-columns:repeat(auto-fit,minmax(420px,1fr))]
        gap-6
        w-full max-w-[90%]
        my-8 mx-auto
        px-4
      "
    >
      {Array.from({ length: count }).map((_, index) => (
        <WeatherCardSkeleton key={index} />
      ))}
    </div>
  );
}
