// src/app/weather/components/weather-cards-loader.jsx
'use client';

import { useEffect, useState } from 'react';
import { hydrateStoreFromSupabase } from '@/app/lib/weather/sync';

/**
 * The following component was generated by Cursor
 */

// Module-level cache to prevent multiple hydrations
let hydrationPromise = null;
let isHydrated = false;

export default function WeatherCardsLoader({ children }) {
  const [isReady, setIsReady] = useState(() => {
    // Check if already hydrated on initial render
    return isHydrated;
  });

  useEffect(() => {
    // Only run in browser
    if (typeof window === 'undefined') {
      return;
    }

    // If already hydrated, we're done
    if (isHydrated) {
      setIsReady(true);
      return;
    }

    // If promise already exists, wait for it
    if (hydrationPromise) {
      hydrationPromise
        .then(() => {
          setIsReady(true);
        })
        .catch(() => {
          // On error, allow retry
          hydrationPromise = null;
          isHydrated = false;
        });
      return;
    }

    // Create new hydration promise
    hydrationPromise = hydrateStoreFromSupabase()
      .then((result) => {
        isHydrated = true;
        hydrationPromise = null;
        setIsReady(true);
        return result;
      })
      .catch((error) => {
        hydrationPromise = null;
        isHydrated = false;
        console.error('Hydration failed:', error);
        // Don't set isReady on error - component will show error state
      });
  }, []);

  // While not ready, return null - Suspense fallback will show
  if (!isReady) {
    return null;
  }

  return children;
}
