// src/app/weather/components/weather-card-skeleton.jsx
'use client';

import React from 'react';
import { Skeleton } from '@/components/ui/skeleton';

/**
 * The following component was generated by Cursor
 */
export default function WeatherCardSkeleton() {
  return (
    <div
      className="relative mt-3 pl px-7 pt-6 pb-5 rounded-2xl
      grid w-full max-w-[500px] min-w-[400px] items-center grid-cols-[2fr_auto] grid-rows-[auto-auto]
      gap-x-[1.2rem] gap-y-1 border border-[rgba(148,163,253,0.14)]"
    >
      {/* Location skeleton */}
      <Skeleton className="flex gap-1 items-end">
        <Skeleton className="h-8 w-32 bg-slate-700 rounded" />
        <Skeleton className="h-4 w-16 bg-slate-700 rounded mb-1" />
      </Skeleton>

      {/* Temperature label skeleton */}
      <Skeleton className="h-6 w-24 bg-slate-700 rounded" />

      {/* Feels like skeleton */}
      <Skeleton className="h-4 w-32 bg-slate-700 rounded" />

      {/* Temperature skeleton */}
      <Skeleton className="h-4 w-20 bg-slate-700 rounded" />
    </div>
  );
}
